cask_args appdir: "/Applications"
tap "heroku/brew"
tap "codeclimate/formulae"
tap "homebrew/core"
tap "homebrew/bundle"
tap "homebrew/services"
tap "caskroom/cask"
brew "node"
brew "openssl"
brew "ruby-build"
brew "rbenv"
brew "rbenv-default-gems"
cask "docker"
cask "github"
cask "google-chrome"
cask "slack"
cask "zoomus"
