cask_args appdir: "/Applications"
tap "homebrew/core"
tap "homebrew/bundle"
tap "homebrew/services"
tap "homebrew/cask"
brew "node"
brew "openssl"
brew "ruby-build"
brew "rbenv"
brew "rbenv-default-gems"
cask "docker"
cask "github"
cask "google-chrome"
cask "iterm2"
cask "slack"
cask "visual-studio-code"
cask "zoomus"
